<a href="https://colab.research.google.com/github/CuicuiZhang01/Cuicui__INFO5731_Spring2026/blob/main/Zhang_Cuicui_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 Assignment 1**

In this assignment, you will work on gathering text data from an open data source via web scraping or API. Following this, you will need to clean the text data and perform syntactic analysis on the data. Follow the instructions carefully and design well-structured Python programs to address each question.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

* **Make sure to submit the cleaned data CSV in the comment section - 10 points**

**Total points**: 100


**Late Submission will have a penalty of 10% reduction for each day after the deadline.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

# Question 1 (25 points)

Write a python program to collect text data from **either of the following sources** and save the data into a **csv file:**

(1) Collect all the customer reviews of a product (you can choose any porduct) on amazon. [atleast 1000 reviews]

(2) Collect the top 1000 User Reviews of a movie recently in 2024 or 2025 (you can choose any movie) from IMDB. [If one movie doesn't have sufficient reviews, collect reviews of atleast 2 or 3 movies]


(3) Collect the **abstracts** of the top 10000 research papers by using the query "machine learning", "data science", "artifical intelligence", or "information extraction" from Semantic Scholar.

(4) Collect all the information of the 904 narrators in the Densho Digital Repository.

(5)**Collect a total of 10000 reviews** of the top 100 most popular software from G2 and Capterra.

In [ ]:
# Taks 1.2 Collect the top 1000 User Reviews of a movie recently in 2024 or 2025 (you can choose any movie) from IMDB. [If one movie doesn't have sufficient reviews, collect reviews of atleast 2 or 3 movies]

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import pandas as pd

# Movie URL (Dune: Part Two has 1000+ reviews)
url = "https://www.imdb.com/title/tt6263850/reviews"

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get(url)

time.sleep(5)

reviews = []

while len(reviews) < 1000:
    try:
        load_more = driver.find_element(By.CLASS_NAME, "ipc-see-more__button")
        driver.execute_script("arguments[0].click();", load_more)
        time.sleep(2)
    except:
        break

    soup = BeautifulSoup(driver.page_source, "html.parser")
    review_blocks = soup.find_all("div", class_="ipc-html-content-inner-div")

    reviews = [r.get_text(strip=True) for r in review_blocks]

    print("Collected:", len(reviews))

driver.quit()

reviews = reviews[:1000]

df = pd.DataFrame({"review": reviews})
df.to_csv("imdb_1000_reviews.csv", index=False)

print("Final Count:", len(reviews))

Collected: 41
Collected: 59
Collected: 82
Collected: 102
Collected: 121
Collected: 143
Collected: 163
Collected: 181
Collected: 202
Collected: 224
Collected: 244
Collected: 265
Collected: 288
Collected: 309
Collected: 327
Collected: 347
Collected: 368
Collected: 388
Collected: 408
Collected: 428
Collected: 449
Collected: 468
Collected: 489
Collected: 507
Collected: 530
Collected: 548
Collected: 569
Collected: 587
Collected: 606
Collected: 626
Collected: 644
Collected: 662
Collected: 681
Collected: 700
Collected: 722
Collected: 741
Collected: 758
Collected: 781
Collected: 803
Collected: 819
Collected: 836
Collected: 854
Collected: 872
Collected: 892
Collected: 912
Collected: 932
Collected: 951
Collected: 968
Collected: 987
Collected: 1006
Final Count: 1000

# Question 2 (15 points)

Write a python program to **clean the text data** you collected in the previous question and save the clean data in a new column in the csv file. The data cleaning steps include: [Code and output is required for each part]

(1) Remove noise, such as special characters and punctuations.

(2) Remove numbers.

(3) Remove stopwords by using the stopwords list.

(4) Lowercase all texts

(5) Stemming.

(6) Lemmatization.

In [ ]:
# Write code for each of the sub parts with proper comments.
import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Load Dataset
df = pd.read_csv("imdb_1000_reviews.csv")

# Display the first 5 rows of the DataFrame
df.head()

                                              review
0  Hugh Jackman is the perfect Wolverine. What a ...
1  What a crazy blast ! Bonkers !!Sooo !...\nWhat...
2  So many Easter Eggs, so true to the comic char...
3  It was painful to watch this movie at times. W...
4  We've waited so long for this moment, and it w...

In [ ]:
# Task 2.1 Remove noise, such as special characters and punctuations

def remove_noise(text):
    return re.sub(r'[^\w\s]', '', str(text))

df["clean_step1"] = df["review"].apply(remove_noise)

df[["review", "clean_step1"]].head()

,review,clean_step1
0,Hugh Jackman is the perfect Wolverine. What a ...,Hugh Jackman is the perfect Wolverine What a f...
1,What a crazy blast ! Bonkers !!Sooo !...\nWhat...,What a crazy blast Bonkers Sooo \nWhat I can ...
2,"So many Easter Eggs, so true to the comic char...",So many Easter Eggs so true to the comic chara...
3,It was painful to watch this movie at times. W...,It was painful to watch this movie at times Wh...
4,"We've waited so long for this moment, and it w...",Weve waited so long for this moment and it was...

In [ ]:
# Task 2.2 Remove numbers

def remove_numbers(text):
    return re.sub(r'\d+', '', text)

df["clean_step2"] = df["clean_step1"].apply(remove_numbers)

df[["clean_step1", "clean_step2"]].head()

,clean_step1,clean_step2
0,Hugh Jackman is the perfect Wolverine What a f...,Hugh Jackman is the perfect Wolverine What a f...
1,What a crazy blast Bonkers Sooo \nWhat I can ...,What a crazy blast Bonkers Sooo \nWhat I can ...
2,So many Easter Eggs so true to the comic chara...,So many Easter Eggs so true to the comic chara...
3,It was painful to watch this movie at times Wh...,It was painful to watch this movie at times Wh...
4,Weve waited so long for this moment and it was...,Weve waited so long for this moment and it was...

In [ ]:
# Task 2.3 Remove stopwords by using the stopwords list

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered = [word for word in tokens if word.lower() not in stop_words]
    return " ".join(filtered)

df["clean_step3"] = df["clean_step2"].apply(remove_stopwords)

df[["clean_step2", "clean_step3"]].head()

,clean_step2,clean_step3
0,Hugh Jackman is the perfect Wolverine What a f...,Hugh Jackman perfect Wolverine fun movie like ...
1,What a crazy blast Bonkers Sooo \nWhat I can ...,crazy blast Bonkers Sooo say movie whole team ...
2,So many Easter Eggs so true to the comic chara...,many Easter Eggs true comic characters may pos...
3,It was painful to watch this movie at times Wh...,painful watch movie times Deadpool known crude...
4,Weve waited so long for this moment and it was...,Weve waited long moment beyond fun wholesome f...

In [ ]:
# Task 2.4 Lowercase all texts
df["clean_step4"] = df["clean_step3"].str.lower()

df[["clean_step3", "clean_step4"]].head()

,clean_step3,clean_step4
0,Hugh Jackman perfect Wolverine fun movie like ...,hugh jackman perfect wolverine fun movie like ...
1,crazy blast Bonkers Sooo say movie whole team ...,crazy blast bonkers sooo say movie whole team ...
2,many Easter Eggs true comic characters may pos...,many easter eggs true comic characters may pos...
3,painful watch movie times Deadpool known crude...,painful watch movie times deadpool known crude...
4,Weve waited long moment beyond fun wholesome f...,weve waited long moment beyond fun wholesome f...

In [ ]:
# Task 2.5 Stemming

stemmer = PorterStemmer()

def apply_stemming(text):
    tokens = word_tokenize(text)
    stemmed = [stemmer.stem(word) for word in tokens]
    return " ".join(stemmed)

df["clean_step5"] = df["clean_step4"].apply(apply_stemming)

df[["clean_step4", "clean_step5"]].head()

,clean_step4,clean_step5
0,hugh jackman perfect wolverine fun movie like ...,hugh jackman perfect wolverin fun movi like di...
1,crazy blast bonkers sooo say movie whole team ...,crazi blast bonker sooo say movi whole team be...
2,many easter eggs true comic characters may pos...,mani easter egg true comic charact may possibl...
3,painful watch movie times deadpool known crude...,pain watch movi time deadpool known crude foul...
4,weve waited long moment beyond fun wholesome f...,weve wait long moment beyond fun wholesom full...

In [ ]:
# Task 2.6 Lemmatization

lemmatizer = WordNetLemmatizer()

def apply_lemmatization(text):
    tokens = word_tokenize(text)
    lemmatized = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(lemmatized)

df["clean_text"] = df["clean_step4"].apply(apply_lemmatization)

df[["clean_step4", "clean_text"]].head()

,clean_step4,clean_text
0,hugh jackman perfect wolverine fun movie like ...,hugh jackman perfect wolverine fun movie like ...
1,crazy blast bonkers sooo say movie whole team ...,crazy blast bonkers sooo say movie whole team ...
2,many easter eggs true comic characters may pos...,many easter egg true comic character may possi...
3,painful watch movie times deadpool known crude...,painful watch movie time deadpool known crude ...
4,weve waited long moment beyond fun wholesome f...,weve waited long moment beyond fun wholesome f...

In [ ]:
# Save Final Cleaned CSV

df.to_csv("imdb_1000_reviews_cleaned.csv", index=False)

print("Cleaned file saved successfully!")

Cleaned file saved successfully!

In [ ]:
# Display dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review       1000 non-null   object
 1   clean_step1  1000 non-null   object
 2   clean_step2  1000 non-null   object
 3   clean_step3  1000 non-null   object
 4   clean_step4  1000 non-null   object
 5   clean_step5  1000 non-null   object
 6   clean_text   1000 non-null   object
dtypes: object(7)
memory usage: 54.8+ KB

# Question 3 (15 points)

Write a python program to **conduct syntax and structure analysis of the clean text** you just saved above. The syntax and structure analysis includes:

(1) **Parts of Speech (POS) Tagging:** Tag Parts of Speech of each word in the text, and calculate the total number of N(oun), V(erb), Adj(ective), Adv(erb), respectively.

(2) **Constituency Parsing and Dependency Parsing:** print out the constituency parsing trees and dependency parsing trees of all the sentences. Using one sentence as an example to explain your understanding about the constituency parsing tree and dependency parsing tree.

(3) **Named Entity Recognition:** Extract all the entities such as person names, organizations, locations, product names, and date from the clean texts, calculate the count of each entity.

In [ ]:
# Your code here
import nltk
from nltk import pos_tag
import pandas as pd
from nltk.tokenize import word_tokenize

df = pd.read_csv("imdb_1000_reviews_cleaned.csv")
df.head()

,review,clean_step1,clean_step2,clean_step3,clean_step4,clean_step5,clean_text
0,Hugh Jackman is the perfect Wolverine. What a ...,Hugh Jackman is the perfect Wolverine What a f...,Hugh Jackman is the perfect Wolverine What a f...,Hugh Jackman perfect Wolverine fun movie like ...,hugh jackman perfect wolverine fun movie like ...,hugh jackman perfect wolverin fun movi like di...,hugh jackman perfect wolverine fun movie like ...
1,What a crazy blast ! Bonkers !!Sooo !...\nWhat...,What a crazy blast Bonkers Sooo \nWhat I can ...,What a crazy blast Bonkers Sooo \nWhat I can ...,crazy blast Bonkers Sooo say movie whole team ...,crazy blast bonkers sooo say movie whole team ...,crazi blast bonker sooo say movi whole team be...,crazy blast bonkers sooo say movie whole team ...
2,"So many Easter Eggs, so true to the comic char...",So many Easter Eggs so true to the comic chara...,So many Easter Eggs so true to the comic chara...,many Easter Eggs true comic characters may pos...,many easter eggs true comic characters may pos...,mani easter egg true comic charact may possibl...,many easter egg true comic character may possi...
3,It was painful to watch this movie at times. W...,It was painful to watch this movie at times Wh...,It was painful to watch this movie at times Wh...,painful watch movie times Deadpool known crude...,painful watch movie times deadpool known crude...,pain watch movi time deadpool known crude foul...,painful watch movie time deadpool known crude ...
4,"We've waited so long for this moment, and it w...",Weve waited so long for this moment and it was...,Weve waited so long for this moment and it was...,Weve waited long moment beyond fun wholesome f...,weve waited long moment beyond fun wholesome f...,weve wait long moment beyond fun wholesom full...,weve waited long moment beyond fun wholesome f...

In [ ]:
# Task 3.1 Apply POS Tagging

def pos_tag_text(text):
    tokens = word_tokenize(str(text))
    return pos_tag(tokens)

df["pos_tags"] = df["clean_text"].apply(pos_tag_text)

df[["clean_text", "pos_tags"]].head()

,clean_text,pos_tags
0,hugh jackman perfect wolverine fun movie like ...,"[(hugh, JJ), (jackman, NN), (perfect, JJ), (wo..."
1,crazy blast bonkers sooo say movie whole team ...,"[(crazy, JJ), (blast, NN), (bonkers, NNS), (so..."
2,many easter egg true comic character may possi...,"[(many, JJ), (easter, JJR), (egg, NN), (true, ..."
3,painful watch movie time deadpool known crude ...,"[(painful, JJ), (watch, NN), (movie, NN), (tim..."
4,weve waited long moment beyond fun wholesome f...,"[(weve, NNS), (waited, VBD), (long, JJ), (mome..."

In [ ]:
# Count Nouns, Verbs, Adjectives, Adverbs
def count_pos(tags):
    noun = 0
    verb = 0
    adj = 0
    adv = 0

    for word, tag in tags:
        if tag.startswith('NN'):
            noun += 1
        elif tag.startswith('VB'):
            verb += 1
        elif tag.startswith('JJ'):
            adj += 1
        elif tag.startswith('RB'):
            adv += 1

    return pd.Series([noun, verb, adj, adv])

df[["Noun_Count", "Verb_Count", "Adj_Count", "Adv_Count"]] = df["pos_tags"].apply(count_pos)

# Calculate Total Counts
total_nouns = df["Noun_Count"].sum()
total_verbs = df["Verb_Count"].sum()
total_adj = df["Adj_Count"].sum()
total_adv = df["Adv_Count"].sum()

print("Total Nouns:", total_nouns)
print("Total Verbs:", total_verbs)
print("Total Adjectives:", total_adj)
print("Total Adverbs:", total_adv)

Total Nouns: 49448
Total Verbs: 19778
Total Adjectives: 23501
Total Adverbs: 9831

In [ ]:
# Task 3,2 Constituency Parsing and Dependency Parsing
# The original review text was used for syntax analysis because heavy text cleaning may distort sentence structure and negatively affect constituency and dependency parsing. Therefore, the first review was selected for analysis.

# Constituency Parsing using Benepar
import warnings
warnings.filterwarnings("ignore")

import spacy
import benepar

# Load spaCy English model
nlp = spacy.load("en_core_web_sm")

# Add Benepar constituency parser
nlp.add_pipe("benepar", config={"model": "benepar_en3"})

# Select the first review (original text)
text = df["review"].iloc[0]

# Process text
doc = nlp(text)

# Print constituency tree for each sentence
for i, sent in enumerate(doc.sents):
    print("\n==============================")
    print(f"Sentence {i+1}: {sent.text}")
    print("==============================")
    print(sent._.parse_string)

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
You're using a T5TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

==============================
Sentence 1: Hugh Jackman is the perfect Wolverine.
==============================
(S (NP (NNP Hugh) (NNP Jackman)) (VP (VBZ is) (NP (DT the) (JJ perfect) (NNP Wolverine))) (. .))

==============================
Sentence 2: What a fun movie.
==============================
(NP (WP What) (DT a) (JJ fun) (NN movie) (. .))

==============================
Sentence 3: I like the dialogue and clever quips with f bombs sprinkled in.
==============================
(S (NP (PRP I)) (VP (VBP like) (NP (NP (DT the) (NML (NML (NN dialogue)) (CC and) (NML (JJ clever) (NNS quips)))) (PP (IN with) (NP (NP (NN f) (NNS bombs)) (VP (VBN sprinkled) (ADVP (RP in))))))) (. .))

==============================
Sentence 4: It's definitely not taking itself too seriously.
==============================
(S (NP (PRP It)) (VP (VBZ 's) (ADVP (RB definitely)) (RB not) (VP (VBG taking) (NP (PRP itself)) (ADVP (RB too) (RB seriously)))) (. .))

==============================
Sentence 5: There is tons of fun cameos I didn't expect!
==============================
(S (NP (EX There)) (VP (VBZ is) (NP (NP (NP (NNS tons)) (PP (IN of) (NP (JJ fun) (NNS cameos)))) (SBAR (S (NP (PRP I)) (VP (VBD did) (RB n't) (VP (VB expect))))))) (. !))

==============================
Sentence 6: I normally watch spoiler videos ahead of time, but I didn't on this occasion
==============================
(S (S (NP (PRP I)) (ADVP (RB normally)) (VP (VBP watch) (NP (NN spoiler) (NNS videos)) (ADVP (RB ahead) (PP (IN of) (NP (NN time)))))) (, ,) (CC but) (S (NP (PRP I)) (VP (VBD did) (RB n't) (PP (IN on) (NP (DT this) (NN occasion))))))

==============================
Sentence 7: and I'm glad I didn't because there was some oh snap moments!
==============================
(S (CC and) (NP (PRP I)) (VP (VBP 'm) (ADJP (JJ glad) (SBAR (S (NP (PRP I)) (VP (VBD did) (RB n't))))) (SBAR (IN because) (S (NP (EX there)) (VP (VBD was) (NP (DT some) (ADJP (RB oh) (JJ snap)) (NNS moments)))))) (. !))

==============================
Sentence 8: It's a very good action packed fun film.
==============================
(S (NP (PRP It)) (VP (VBZ 's) (NP (DT a) (ADJP (RB very) (JJ good)) (ADJP (NN action) (VBN packed)) (NN fun) (NN film))) (. .))

==============================
Sentence 9: The breaking the Fox jokes and speaking to the camera jokes are too funny.
==============================
(S (NP (NP (DT The) (VP (VBG breaking) (NP (DT the) (NNP Fox) (NNS jokes)))) (CC and) (VP (VBG speaking) (PP (IN to) (NP (DT the) (NN camera) (NNS jokes))))) (VP (VBP are) (ADJP (RB too) (JJ funny))) (. .))

==============================
Sentence 10: I can definitely see more sequels for these two on the horizon.
==============================
(S (NP (PRP I)) (VP (MD can) (ADVP (RB definitely)) (VP (VB see) (NP (NP (JJR more) (NNS sequels)) (PP (IN for) (NP (DT these) (CD two)))) (PP (IN on) (NP (DT the) (NN horizon))))) (. .))

==============================
Sentence 11: They are promoting this movie hard I just watched these two on Hot Ones eating chicken wings They make a dynamic duo.
==============================
(S (NP (PRP They)) (VP (VBP are) (VP (VP (VBG promoting) (NP (DT this) (NN movie)) (ADVP (RB hard))) (NP (PRP I)) (ADVP (RB just)) (VP (VP (VBD watched) (NP (DT these) (CD two)) (PP (IN on) (NP (NP (NNP Hot) (NNPS Ones)) (VP (VBG eating) (NP (NN chicken) (NNS wings)))))) (NP (PRP They)) (VP (VBP make) (NP (DT a) (JJ dynamic) (NN duo)))))) (. .))

==============================
Sentence 12: Until your 90 Wolverine ...until your 90 lol.
==============================
(FRAG (PP (IN Until) (NP (PRP$ your) (CD 90) (NNP Wolverine))) (: ...) (PP (IN until) (NP (NP (PRP$ your) (CD 90)) (RB lol))) (. .))

#### We use the first sentence of this review as an example:“Hugh Jackman is the perfect Wolverine.”
#### The constituency parsing tree shows the phrase structure of the sentence. The whole sentence is labeled as S. It is divided into a noun phrase (NP), “Hugh Jackman,” which functions as the subject, and a verb phrase (VP), “is the perfect Wolverine.” Within the VP, “the perfect Wolverine” forms another noun phrase. This analysis illustrates how words are grouped into hierarchical phrase structures within a sentence

In [ ]:
# Dependency Parsing using spaCy
# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Select the first review
text = df["review"].iloc[0]

# Process text
doc = nlp(text)

# Print dependency relations for each sentence
for i, sent in enumerate(doc.sents):
    print("\n==============================")
    print(f"Sentence {i+1}: {sent.text}")
    print("==============================")

    for token in sent:
        print(token.text, "-->", token.dep_, "-->", token.head.text)

==============================
Sentence 1: Hugh Jackman is the perfect Wolverine.
==============================
Hugh --> compound --> Jackman
Jackman --> nsubj --> is
is --> ROOT --> is
the --> det --> Wolverine
perfect --> amod --> Wolverine
Wolverine --> attr --> is
. --> punct --> is

==============================
Sentence 2: What a fun movie.
==============================
What --> det --> movie
a --> det --> movie
fun --> compound --> movie
movie --> ROOT --> movie
. --> punct --> movie

==============================
Sentence 3: I like the dialogue and clever quips with f bombs sprinkled in.
==============================
I --> nsubj --> like
like --> ROOT --> like
the --> det --> dialogue
dialogue --> nsubj --> sprinkled
and --> cc --> dialogue
clever --> amod --> quips
quips --> conj --> dialogue
with --> prep --> dialogue
f --> compound --> bombs
bombs --> pobj --> with
sprinkled --> ccomp --> like
in --> prt --> sprinkled
. --> punct --> like

==============================
Sentence 4: It's definitely not taking itself too seriously.
==============================
It --> nsubj --> taking
's --> aux --> taking
definitely --> advmod --> taking
not --> neg --> taking
taking --> ROOT --> taking
itself --> dobj --> taking
too --> advmod --> seriously
seriously --> advmod --> taking
. --> punct --> taking

==============================
Sentence 5: There is tons of fun cameos I didn't expect!
==============================
There --> expl --> is
is --> ROOT --> is
tons --> attr --> is
of --> prep --> tons
fun --> amod --> cameos
cameos --> pobj --> of
I --> nsubj --> expect
did --> aux --> expect
n't --> neg --> expect
expect --> relcl --> tons
! --> punct --> is

==============================
Sentence 6: I normally watch spoiler videos ahead of time, but I didn't on this occasion
==============================
I --> nsubj --> watch
normally --> advmod --> watch
watch --> ROOT --> watch
spoiler --> compound --> videos
videos --> dobj --> watch
ahead --> advmod --> watch
of --> prep --> ahead
time --> pobj --> of
, --> punct --> watch
but --> cc --> watch
I --> nsubj --> did
did --> conj --> watch
n't --> neg --> on
on --> prep --> did
this --> det --> occasion
occasion --> pobj --> on

==============================
Sentence 7: and I'm glad I didn't because there was some oh snap moments!
==============================
and --> cc --> 'm
I --> nsubj --> 'm
'm --> ROOT --> 'm
glad --> acomp --> 'm
I --> nsubj --> did
did --> ccomp --> glad
n't --> neg --> did
because --> mark --> was
there --> expl --> was
was --> advcl --> 'm
some --> det --> moments
oh --> intj --> moments
snap --> amod --> moments
moments --> attr --> was
! --> punct --> 'm

==============================
Sentence 8: It's a very good action packed fun film.
==============================
It --> nsubj --> 's
's --> ROOT --> 's
a --> det --> film
very --> advmod --> good
good --> amod --> film
action --> npadvmod --> packed
packed --> amod --> film
fun --> compound --> film
film --> attr --> 's
. --> punct --> 's

==============================
Sentence 9: The breaking the Fox jokes and speaking to the camera jokes are too funny.
==============================
The --> det --> breaking
breaking --> csubj --> are
the --> det --> jokes
Fox --> compound --> jokes
jokes --> dobj --> breaking
and --> cc --> breaking
speaking --> conj --> breaking
to --> prep --> speaking
the --> det --> jokes
camera --> compound --> jokes
jokes --> pobj --> to
are --> ROOT --> are
too --> advmod --> funny
funny --> acomp --> are
. --> punct --> are

==============================
Sentence 10: I can definitely see more sequels for these two on the horizon.
==============================
I --> nsubj --> see
can --> aux --> see
definitely --> advmod --> see
see --> ROOT --> see
more --> amod --> sequels
sequels --> dobj --> see
for --> prep --> sequels
these --> det --> two
two --> pobj --> for
on --> prep --> see
the --> det --> horizon
horizon --> pobj --> on
. --> punct --> see

==============================
Sentence 11: They are promoting this movie hard I just watched these two on Hot Ones eating chicken wings They make a dynamic duo.
==============================
They --> nsubj --> promoting
are --> aux --> promoting
promoting --> ROOT --> promoting
this --> det --> movie
movie --> dobj --> promoting
hard --> advmod --> promoting
I --> nsubj --> watched
just --> advmod --> watched
watched --> conj --> promoting
these --> det --> two
two --> dobj --> watched
on --> prep --> watched
Hot --> compound --> Ones
Ones --> pobj --> on
eating --> advcl --> watched
chicken --> compound --> wings
wings --> dobj --> eating
They --> nsubj --> make
make --> ccomp --> promoting
a --> det --> duo
dynamic --> amod --> duo
duo --> dobj --> make
. --> punct --> promoting

==============================
Sentence 12: Until your 90 Wolverine ...until your 90 lol.
==============================
Until --> ROOT --> Until
your --> poss --> Wolverine
90 --> nummod --> Wolverine
Wolverine --> pobj --> Until
... --> punct --> Until
until --> prep --> ...
your --> poss --> lol
90 --> nummod --> lol
lol --> pobj --> until
. --> punct --> Until

#### We use the same sentence as an example: “Hugh Jackman is the perfect Wolverine.”

#### The dependency parsing tree shows the grammatical relationships between words. The main verb “is” is labeled as the ROOT, meaning it is the central word of the sentence. “Jackman” is the subject (nsubj) of “is,” and “Hugh” modifies “Jackman” as a compound name. “Wolverine” functions as the complement (attr) of the verb “is.” The word “perfect” modifies “Wolverine” as an adjective (amod), and “the” acts as a determiner (det). This analysis focuses on how words are connected to each other and their grammatical roles in the sentence.

In [ ]:
# Task3.3 Named Entity Recognition
# To better identify and extract entities such as person names, organizations, locations, product names, and dates, we chose to perform the analysis on the original review text. This ensures that the full contextual and structural information of the sentences is preserved, allowing for more accurate named entity recognition.

# Load the English language model
nlp = spacy.load("en_core_web_sm")

# Extract Named Entities
def extract_entities(text):
    doc = nlp(str(text))
    entities = []

    for ent in doc.ents:
        entities.append((ent.text, ent.label_))

    return entities

# Apply entity extraction to original reviews
df["entities"] = df["review"].apply(extract_entities)

df[["review", "entities"]].head()

,review,entities
0,Hugh Jackman is the perfect Wolverine. What a ...,"[(Hugh Jackman, PERSON), (Wolverine, PERSON), ..."
1,What a crazy blast ! Bonkers !!Sooo !...\nWhat...,"[(Sooo, PERSON), (second, ORDINAL), (first, OR..."
2,"So many Easter Eggs, so true to the comic char...","[(Easter Eggs, PERSON), (MCU, ORG), (the last ..."
3,It was painful to watch this movie at times. W...,"[(Deadpool, PERSON), (Deadpool, ORG), (first, ..."
4,"We've waited so long for this moment, and it w...","[(Ryan Reynolds, PERSON), (Hugh Jackman, GPE),..."

In [ ]:
from collections import Counter

# Flatten all entities into a single list
all_entities = []

for entity_list in df["entities"]:
    all_entities.extend(entity_list)

# Count entities by label
entity_counts = Counter([label for text, label in all_entities])

print("Entity Counts by Type:")
print(entity_counts)

Entity Counts by Type:
Counter({'ORG': 3352, 'PERSON': 2736, 'CARDINAL': 1302, 'GPE': 755, 'ORDINAL': 752, 'DATE': 665, 'WORK_OF_ART': 246, 'TIME': 177, 'PRODUCT': 156, 'NORP': 69, 'FAC': 56, 'PERCENT': 40, 'LOC': 24, 'MONEY': 21, 'QUANTITY': 18, 'EVENT': 10, 'LAW': 7, 'LANGUAGE': 7})

# **Following Questions must answer using AI assitance**

#Question 4 (20 points).

Q4. (PART-1)
Web scraping data from the GitHub Marketplace to gather details about popular actions. Using Python, the process begins by sending HTTP requests to multiple pages of the marketplace (1000 products), handling pagination through dynamic page numbers. The key details extracted include the product name, a short description, and the URL.

 The extracted data is stored in a structured CSV format with columns for product name, description, URL, and page number. A time delay is introduced between requests to avoid server overload. ChatGPT can assist by helping with the parsing of HTML, error handling, and generating reports based on the data collected.

 The goal is to complete the scraping within a specified time limit, ensuring that the process is efficient and adheres to GitHub’s usage guidelines.

(PART -2)

1.   **Preprocess Data**: Clean the text by tokenizing, removing stopwords, and converting to lowercase.

2. Perform **Data Quality** operations.


Preprocessing:
Preprocessing involves cleaning the text by removing noise such as special characters, HTML tags, and unnecessary whitespace. It also includes tasks like tokenization, stopword removal, and lemmatization to standardize the text for analysis.

Data Quality:
Data quality checks ensure completeness, consistency, and accuracy by verifying that all required columns are filled and formatted correctly. Additionally, it involves identifying and removing duplicates, handling missing values, and ensuring the data reflects the true content accurately.

Github MarketPlace page:
https://github.com/marketplace?type=actions

In [ ]:
import time
import random
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import NoSuchElementException

# Configure Chrome WebDriver
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

# Initialize WebDriver using ChromeDriverManager
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=chrome_options
)

# Base URL with dynamic pagination
BASE_URL = "https://github.com/marketplace?type=actions&page={}"

# Store all scraped data
all_data = []

# Set number of pages to scrape
# Adjust this carefully to avoid overloading the server
max_pages = 55

# Start Scraping Process
for page in range(1, max_pages + 1):
    url = BASE_URL.format(page)
    if page % 10 == 0:
        print(f"Scraping page {page}...")

    try:
        # Load the page
        driver.get(url)

        # Wait for dynamic JavaScript content to load
        time.sleep(random.uniform(3, 5))

        # Locate all product cards
        # Each card contains title + description
        items = driver.find_elements(
            By.CSS_SELECTOR,
            "div[data-testid='non-featured-item']"
        )

        # Stop if no products found
        if not items:
            print("No more products found.")
            break

        # Loop through each product card
        for item in items:
            try:
                # Extract product name
                name = item.find_element(
                    By.CSS_SELECTOR,
                    "a.line-clamp-1"
                ).text.strip()

                # Extract description
                try:
                    description = item.find_element(
                        By.CSS_SELECTOR,
                        "p.line-clamp-2"
                    ).text.strip()
                except NoSuchElementException:
                    description = "N/A"

                # Extract product URL
                link = item.find_element(
                    By.CSS_SELECTOR,
                    "a.line-clamp-1"
                ).get_attribute("href")

                # Append to list
                all_data.append({
                    "product_name": name,
                    "description": description,
                    "url": link,
                    "page_number": page
                })

            except Exception as e:
                print(f"Error extracting product: {e}")
                continue

    except Exception as e:
        print(f"Error loading page {page}: {e}")
        continue

    # Introduce delay between page requests
    time.sleep(random.uniform(2, 4))


# Close Browser
driver.quit()

# Convert data to DataFrame
df = pd.DataFrame(all_data)

# Save data to CSV
df.to_csv("github_marketplace_actions.csv", index=False)

print("\nScraping completed.")
print(f"Total records collected: {len(df)}")

Scraping page 10...
Scraping page 20...
Scraping page 30...
Scraping page 40...
Scraping page 50...

Scraping completed.
Total records collected: 1100

In [ ]:
import pandas as pd
# Load CSV file
df = pd.read_csv("github_marketplace_actions.csv")

# Keep only the first 1000 records as required
df = df.head(1000)

# Save the updated dataset into a new CSV file
df.to_csv("github_marketplace_actions_1000.csv", index=False)

# Display dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_name  1000 non-null   object
 1   description   999 non-null    object
 2   url           1000 non-null   object
 3   page_number   1000 non-null   int64
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

In [ ]:
# Task 4.1 Preprocess Data

import re
import pandas as pd
from bs4 import BeautifulSoup
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Initialize tools
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    if pd.isna(text):
        return ""

    # 1. Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()

    # 2. Remove special characters and numbers
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # 3. Convert to lowercase
    text = text.lower()

    # 4. Remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    # 5. Tokenization
    tokens = word_tokenize(text)

    # 6. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 7. Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

# Apply preprocessing to description column
df["clean_description"] = df["description"].apply(preprocess_text)

# Save cleaned data
df.to_csv("github_actions_cleaned.csv", index=False)

print("Preprocessing completed successfully.")

Preprocessing completed successfully.

/var/folders/gj/mv0l2vm12vb31svnxq9q3ry00000gp/T/ipykernel_67274/2542584303.py:19: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text = BeautifulSoup(text, "html.parser").get_text()

In [ ]:
# Task 4.2 Data Quality Check

# Load CSV file
df = pd.read_csv("github_actions_cleaned.csv")

# Display the first 5 rows of the dataset
df.head()

,product_name,description,url,page_number,clean_description
0,TruffleHog OSS,Find and verify leaked credentials in your sou...,https://github.com/marketplace/actions/truffle...,1,find verify leaked credential source code
1,Metrics embed,An infographics generator with 40+ plugins and...,https://github.com/marketplace/actions/metrics...,1,infographics generator plugins option display ...
2,yq - portable yaml processor,"create, read, update, delete, merge, validate ...",https://github.com/marketplace/actions/yq-port...,1,create read update delete merge validate yaml
3,Super-Linter,Super-linter is a ready-to-run collection of l...,https://github.com/marketplace/actions/super-l...,1,superlinter readytorun collection linters code...
4,Rebuild Armbian and Kernel,"Support Amlogic, Rockchip and Allwinner boxes",https://github.com/marketplace/actions/rebuild...,1,support amlogic rockchip allwinner box

In [ ]:
import pandas as pd

# 1. Check Completeness

# Check missing values in each column
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
product_name         0
description          1
url                  0
page_number          0
clean_description    1
dtype: int64

In [ ]:
# Fill missing descriptions with empty string
df["description"] = df["description"].fillna("")
df["clean_description"] = df["clean_description"].fillna("")

# Check missing values in each column
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
product_name         0
description          0
url                  0
page_number          0
clean_description    0
dtype: int64

In [ ]:
# 2. Check Duplicates

# Count duplicates before removal
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [ ]:
# 3. Check Consistency

# Ensure page_number is numeric
df["page_number"] = pd.to_numeric(df["page_number"], errors="coerce")

# Remove rows where page_number is missing after conversion
df = df.dropna(subset=["page_number"])

# 4. Validate URL Format

# Keep only rows where URL starts with https
df = df[df["url"].str.startswith("https", na=False)]

print("Invalid URLs removed.")

Invalid URLs removed.

In [ ]:
# 5. Trim Extra Whitespace

df["product_name"] = df["product_name"].str.strip()
df["description"] = df["description"].str.strip()

# 6. Final Data Summary

print("Final dataset shape:", df.shape)

Final dataset shape: (1000, 5)

In [ ]:
# Save cleaned dataset
df.to_csv("github_actions_final.csv", index=False)
print("Data Quality checks completed successfully.")

Data Quality checks completed successfully.

#Question 5 (20 points)

PART 1:
Web Scrape  tweets from Twitter using the Tweepy API, specifically targeting hashtags related to subtopics (machine learning or artificial intelligence.)
The extracted data includes the tweet ID, username, and text.

Part 2:
Perform data cleaning procedures

A final data quality check ensures the completeness and consistency of the dataset. The cleaned data is then saved into a CSV file for further analysis.


**Note**

1.   Follow tutorials provided in canvas to obtain api keys. Use ChatGPT to get the code. Make sure the file is downloaded and saved.
2.   Make sure you divide GPT code as shown in tutorials, dont make multiple requestes.

In [ ]:
# Task 5.1
import tweepy
import pandas as pd
from dotenv import load_dotenv
import os

# 1. Authentication
# Load environment variables from a .env file
load_dotenv()

# Initialize Twitter API client with Bearer Token for authentication
client = tweepy.Client(bearer_token=os.getenv("TWITTER_X_BEARER_TOKEN"))

# 2. Define Search Query
# Search for hashtags related to Machine Learning or AI
query = "(#MachineLearning OR #ArtificialIntelligence) -is:retweet lang:en"

# 3. Fetch Tweets
tweets = client.search_recent_tweets(
    query=query,
    max_results=100,
    tweet_fields=["id", "text", "author_id"],
    expansions=["author_id"],
    user_fields=["username"]
)

users = {u["id"]: u["username"] for u in tweets.includes["users"]}

# 4. Store Data
data = []

if tweets.data:
    for tweet in tweets.data:
        data.append([
            tweet.id,
            users[tweet.author_id],
            tweet.text
        ])

# Create DataFrame
df = pd.DataFrame(data, columns=["tweet_id", "username", "text"])

# Save to CSV
df.to_csv("ml_ai_tweets.csv", index=False)

print("Tweet scraping completed successfully.")
print("Total tweets collected:", len(df))

Tweet scraping completed successfully.
Total tweets collected: 100

In [ ]:
# Task 5.2
import pandas as pd

# Step 1: Load the dataset
df = pd.read_csv("ml_ai_tweets.csv")

print("Original Shape:", df.shape)
df.head()

Original Shape: (100, 3)

,tweet_id,username,text
0,2027962868503629922,SteveKlinko,Click here: https://t.co/DQjPESKi0v to see how...
1,2027962826204320248,JiaMonroe,We aren't just using AI; we’re living through ...
2,2027962498566308003,JiaMonroe,"Alpha lives at the intersection of Physics, Ma..."
3,2027962255602864520,jcrelc_journal,"One classroom, many learners—can AI help reach..."
4,2027961190530310444,nordicinst,Times of India @timesofindia: Focus on job cre...

In [ ]:
# Step 2: Data Quality Check

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
tweet_id    0
username    0
text        0
dtype: int64

In [ ]:
# Remove duplicate tweet IDs
df = df.drop_duplicates(subset=["tweet_id"])
df.shape

(100, 3)

In [ ]:
# Step 3: Clean Text Data

# Remove leading/trailing spaces
df["text"] = df["text"].str.strip()

# Convert text to lowercase (optional for NLP analysis)
df["text"] = df["text"].str.lower()

# Remove extra spaces inside text
df["text"] = df["text"].str.replace(r"\s+", " ", regex=True)

# Step 4: Final Data Check
df.head()

,tweet_id,username,text
0,2027962868503629922,SteveKlinko,click here: https://t.co/dqjpeski0v to see how...
1,2027962826204320248,JiaMonroe,we aren't just using ai; we’re living through ...
2,2027962498566308003,JiaMonroe,"alpha lives at the intersection of physics, ma..."
3,2027962255602864520,jcrelc_journal,"one classroom, many learners—can ai help reach..."
4,2027961190530310444,nordicinst,times of india @timesofindia: focus on job cre...

In [ ]:
# Step 5: Save Cleaned Dataset

df.to_csv("ml_ai_tweets_cleaned.csv", index=False)

print("Saved: ml_ai_tweets_cleaned.csv")

Saved: ml_ai_tweets_cleaned.csv

# Mandatory Question (5 points)

Provide your thoughts on the assignment. What did you find challenging, and what aspects did you enjoy? Your opinion on the provided time to complete the assignment.

This assignment was interesting and practical. The most challenging part was web scraping and syntax analysis, especially parsing trees. It required careful coding and understanding of NLP concepts.

I enjoyed learning how to collect data from APIs and websites and how to clean and analyze text data. It helped me understand the full process of working with real-world data.

The assignment took a lot of time because it included many steps. The time given was reasonable, but it required good time management.

Overall, it was challenging but very helpful for improving my programming and data analysis skills.